version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=neuraload
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./data:/data
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://postgres:password@db:5432/neuraload
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db

volumes:
  postgres_data:
