services:
  postgres:
    image: postgres:15-alpine
    container_name: neuraload_postgres
    environment:
      POSTGRES_DB: neuraload_db
      POSTGRES_USER: neuraload_user
      POSTGRES_PASSWORD: neuraload_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neuraload_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: neuraload_db
      DB_USER: neuraload_user
      DB_PASSWORD: neuraload_password
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: neuraload_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neuraload.com
      PGADMIN_DEFAULT_PASSWORD: admin123456
    ports:
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
