# Generated by Django 4.2.7 on 2025-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_unique_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('vehicles_model_name', models.CharField(max_length=100)),
                ('max_load_capacity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='UserDeviceLink',
            fields=[
                ('user_device_id', models.AutoField(primary_key=True, serialize=False)),
                ('linked_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='vehicle.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_device_links',
                'unique_together': {('user', 'device')},
            },
        ),
    ]
