# Generated by Django 4.2.7 on 2025-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driving', '0001_initial'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingData',
            fields=[
                ('logging_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=20)),
                ('vehicle_speed_kmh', models.CharField(max_length=10)),
                ('gps_x', models.CharField(max_length=20)),
                ('gps_y', models.CharField(max_length=20)),
                ('gps_heading', models.IntegerField()),
                ('rpm', models.CharField(max_length=10)),
                ('brake_signal', models.IntegerField()),
                ('accel_vx', models.IntegerField()),
                ('accel_vy', models.IntegerField()),
                ('laser_sensor_data', models.JSONField()),
                ('estimated_load_kg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.device')),
                ('driving_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driving.drivinghistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logging_data',
            },
        ),
    ]
