# Generated by Django 4.2.7 on 2025-06-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingHistory',
            fields=[
                ('driving_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timestamp', models.CharField(max_length=20)),
                ('end_timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('start_estimated_load_kg', models.FloatField()),
                ('end_estimated_load_kg', models.FloatField(blank=True, null=True)),
                ('total_driving_distance', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driving_history',
            },
        ),
    ]
